### PR TITLE
Update wrapper.dart, add support for macOS

### PR DESCRIPTION
**Pull request by dangfan**

### CODE REVIEW

**Comment by jjanku** [comment]
Hi, thanks for the PR! The proposed change definitely goes in the right direction, but I'm afraid that more changes may be necessary. The following definitions are all macOS-specific:

* https://github.com/jjanku/dart_pcsc/blob/d3f0f228a92d35c691d91ad39aec197e276f82f7/include/pcsc/wintypes.h#L46-L75
* https://github.com/jjanku/dart_pcsc/blob/d3f0f228a92d35c691d91ad39aec197e276f82f7/include/pcsc/pcsclite.h#L63-L76
* https://github.com/jjanku/dart_pcsc/blob/d3f0f228a92d35c691d91ad39aec197e276f82f7/include/pcsc/pcsclite.h#L91-L97

Have you tested this in macOS?

**Comment by dangfan** [comment]
Yes, I've tested this on macOS. I use your package to build a package called [fido2](https://pub.dev/packages/fido2), and my test runs on macOS. Everything works fine.

**Comment by jjanku** [comment]
Great, in that case, let's merge this.

**Comment by jjanku** [comment]
Released as v2.0.1, see https://pub.dev/packages/dart_pcsc/versions/2.0.1. Thanks again.

**Pull request merged**
